version: '3'

services:
  backend:
    build: ./backend
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root

  keycloak:
    image: jboss/keycloak:15.0.0
    # volumes:
    #   - ./keycloak/:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080
